FROM registry.gitlab.com/grmtech-oss/docker-images/ubuntu-php
 
##### Section 2: Container specific packages #####
# Install php ssh2 to be able to SFTP server connect
#RUN apt-get -y update
#RUN apt-get install -y php-ssh2

#CMD ["/usr/bin/supervisord", "-n","-c","/etc/supervisor/supervisord.conf"]